### ISSUE TITLE
bug due upgrade ha?

### ISSUE THREAD

**Issue by edegraaff** [heinoldenhuis/home_assistant_omnik_solar#11]
after upgrade to 2021.6.3 i get errrors do others have similar errors ? 

Error while setting up omnik_inverter platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/omnik_inverter/sensor.py", line 81, in setup_platform
    entities.append(OmnikInverterSensor(data, sensor_type, name, cache, cache_name))
  File "/config/custom_components/omnik_inverter/sensor.py", line 189, in __init__
    self.update()
  File "/config/custom_components/omnik_inverter/sensor.py", line 219, in update
    self._data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 280, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/omnik_inverter/sensor.py", line 108, in _update
    fp.close()
UnboundLocalError: local variable 

it always worked fine

eelco

**Comment by edegraaff** [comment]
reboot fixed
